# Build order: avr-binutils -> avr-gcc -> avr-libc
name       : avr-libc
version    : 2.0.0
release    : 3
source     :
    - https://download.savannah.gnu.org/releases/avr-libc/avr-libc-2.0.0.tar.bz2 : b2dd7fd2eefd8d8646ef6a325f6f0665537e2f604ed02828ced748d49dc85b97
license    : BSD-3-Clause
summary    : A C runtime library for AVR
component  : programming
description: |
    The C runtime library for the AVR family of microcontrollers
strip      : no
builddeps  :
    - avr-gcc
rundeps    :
    - avr-gcc
environment: |
    export TARGET=avr
    export PREFIX=/usr/share/$TARGET
    unset CC
    source /usr/share/defaults/etc/profile.d/50-avr-toolchain-path.sh
setup      : |
    ./bootstrap

    ./configure \
        --build=%HOST% \
        --prefix=$PREFIX \
        --host=$TARGET
build      : |
    %make
install    : |
    %make_install
